
export const dummyQuestions = [
  {
    id: 1,
    text: "The weather outside was extremely pleasant and hence we decided to ______.",
    options: [
      { id: 'a', text: "employ this rare opportunity for writing letters" },
      { id: 'b', text: "enjoy a morning ride in the open" },
      { id: 'c', text: "refrain from going out for a morning walk" },
      { id: 'd', text: "utilize our time watching the television" },
    ],
    correctAnswer: 'b',
    hint: "Think about what one would do on a pleasant morning outdoors.",
    explanation: "The phrase 'extremely pleasant' suggests an activity that would allow one to enjoy the weather. 'Enjoy a morning ride in the open' fits this perfectly, implying taking advantage of the good weather.",
  },
  {
    id: 2,
    text: "Which of the following is a prime number?",
    options: [
      { id: 'a', text: "4" },
      { id: 'b', text: "9" },
      { id: 'c', text: "11" },
      { id: 'd', text: "15" },
    ],
    correctAnswer: 'c',
    hint: "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself.",
    explanation: "A prime number is a natural number greater than 1 that has no positive divisors other than 1 and itself. 4 = 2x2, 9 = 3x3, 15 = 3x5. Only 11 is divisible only by 1 and 11.",
  },
  {
    id: 3,
    text: "What is the capital of France?",
    options: [
      { id: 'a', text: "Berlin" },
      { id: 'b', text: "Madrid" },
      { id: 'c', text: "Rome" },
      { id: 'd', text: "Paris" },
    ],
    correctAnswer: 'd',
    hint: "It's a major European city known for its art and culture.",
    explanation: "Paris is the capital and most populous city of France.",
  },
  {
    id: 4,
    text: "Which planet is known as the 'Red Planet'?",
    options: [
      { id: 'a', text: "Earth" },
      { id: 'b', text: "Mars" },
      { id: 'c', text: "Jupiter" },
      { id: 'd', text: "Venus" },
    ],
    correctAnswer: 'b',
    hint: "It's the fourth planet from the Sun.",
    explanation: "Mars is often referred to as the 'Red Planet' due to its reddish appearance, which is caused by iron oxide (rust) on its surface.",
  },
  {
    id: 5,
    text: "What is the chemical symbol for water?",
    options: [
      { id: 'a', text: "O2" },
      { id: 'b', text: "H2O" },
      { id: 'c', text: "CO2" },
      { id: 'd', text: "NaCl" },
    ],
    correctAnswer: 'b',
    hint: "It involves hydrogen and oxygen.",
    explanation: "The chemical symbol for water is H2O, meaning it is composed of two hydrogen atoms and one oxygen atom.",
  },
  {
    id: 6,
    text: "Who painted the Mona Lisa?",
    options: [
      { id: 'a', text: "Vincent van Gogh" },
      { id: 'b', text: "Pablo Picasso" },
      { id: 'c', text: "Leonardo da Vinci" },
      { id: 'd', text: "Claude Monet" },
    ],
    correctAnswer: 'c',
    hint: "He was a famous Italian Renaissance artist and inventor.",
    explanation: "The Mona Lisa was painted by Leonardo da Vinci, an Italian polymath of the High Renaissance.",
  },
  {
    id: 7,
    text: "What is the largest ocean on Earth?",
    options: [
      { id: 'a', text: "Atlantic Ocean" },
      { id: 'b', text: "Indian Ocean" },
      { id: 'c', text: "Arctic Ocean" },
      { id: 'd', text: "Pacific Ocean" },
    ],
    correctAnswer: 'd',
    hint: "It covers about one-third of the surface of the Earth.",
    explanation: "The Pacific Ocean is the largest and deepest of Earth's oceanic divisions.",
  },
  {
    id: 8,
    text: "How many continents are there?",
    options: [
      { id: 'a', text: "5" },
      { id: 'b', text: "6" },
      { id: 'c', text: "7" },
      { id: 'd', text: "8" },
    ],
    correctAnswer: 'c',
    hint: "Think about North America, South America, Europe, Asia, Africa, Australia...",
    explanation: "There are generally considered to be seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.",
  },
  {
    id: 9,
    text: "What is the fastest land animal?",
    options: [
      { id: 'a', text: "Lion" },
      { id: 'b', text: "Cheetah" },
      { id: 'c', text: "Gazelle" },
      { id: 'd', text: "Horse" },
    ],
    correctAnswer: 'b',
    hint: "It's known for its incredible speed and spotted coat.",
    explanation: "The cheetah is the fastest land animal, capable of running at speeds of up to 120 km/h (75 mph) over short distances.",
  },
  {
    id: 10,
    text: "Which gas do plants absorb from the atmosphere?",
    options: [
      { id: 'a', text: "Oxygen" },
      { id: 'b', text: "Nitrogen" },
      { id: 'c', text: "Carbon Dioxide" },
      { id: 'd', text: "Hydrogen" },
    ],
    correctAnswer: 'c',
    hint: "It's essential for photosynthesis.",
    explanation: "Plants absorb carbon dioxide from the atmosphere for photosynthesis, the process by which they convert light energy into chemical energy.",
  },
];
