// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jhiafsazllzimnykfiut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpoaWFmc2F6bGx6aW1ueWtmaXV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjg3MzEsImV4cCI6MjA2NTUwNDczMX0.xydPjNHjUZX_5LTX5dWq_kXFegmttmlQlPQ7D-iR1yw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);